### PR TITLE
Add Overlay

### PR DESCRIPTION
**Pull request by efritz**
This PR introduced the `Overlay` function, which allows a service container to be wrapped in a set of additional, immutable services. This works with both `Get` and `Inject` functions, allowing a service to be temporarily replaced in the base container.

This will be useful when specific loggers or context-specific services should be injected in all downstream handlers for a certain process, task, or request.

### CODE REVIEW

**Comment by aphistic** [comment]
I like the idea, it can be used for more than just the logging I'd initially mentioned! How would you see this being used inside a bootstrapper method, such as https://github.com/aphistic/softcopy/blob/master/cmd/softcopy-server/main.go#L27 ? Would it become an additional `nacelle.WithInitializerServiceContainer` or `nacelle.WithProcessServiceContainer`? If I wanted to add additional fields to the logger configured by nacelle as the default, how would I do that? The `ServiceContainer` isn't initialized by the time the Bootstrapper function is called, is it? If so, would I just get the logger from the existing container and then add that as an overlay to the initializer/process?

This is what I'm imagining it would look like, is it right?
```go
func (runner nacelle.ProcessContainer, container nacelle.ServiceContainer) error {
	// This or some nicer method to move this out of the bootstrapper
	rawLogger, err := container.Get("logger")
	if err != nil {
		return err
	}
	logger, ok := rawLogger.(nacelle.Logger)
	if !ok {
		return fmt.Errorf("logger isn't a nacelle logger")
	}

	runner.RegisterInitializer(
		api.NewInitializer(),
		nacelle.WithInitializerName("api"),
		nacelle.WithInitializerOverlay(nacelle.Overlay(
			"logger": logger.WithFields(
				"service": "api",
			),
		),)
	)
	
	runner.RegisterProcess(
		apiserver.NewProcess(),
		nacelle.WithProcessName("apiserver"),
		nacelle.WithProcessOverlay(nacelle.Overlay(
			"logger": logger.WithFields(
				"service": "apiserver",
			),
		),)
	)
}
```

**Comment by efritz** [comment]
My idea was to have the go-nacelle/process create a shim service and logger instance with any additional fields you've applied to an initializer or process. So really the setup methods would be something like:

```go
func (runner nacelle.ProcessContainer, container nacelle.ServiceContainer) error {
	runner.RegisterInitializer(
		api.NewInitializer(),
		nacelle.WithInitializerName("api"),
		nacelle.WithLogFields(map[string]string{
			"service": "api",
		}),
	)
	
	runner.RegisterProcess(
		apiserver.NewProcess(),
		nacelle.WithProcessName("apiserver"),
		nacelle.WithLogFields(map[string]string{
			"service": "apiserver",
		}),
	)
}
```

Names subject to change, of course!

**Comment by efritz** [comment]
And if you have an initializer/process name, this could be done automatically (but would still allow for additional fields to be applied).

**Comment by aphistic** [comment]
Ahh, gotcha. I didn't notice this was in the service repo at first!

**Pull request merged**
